create table if not exists public.music_analysis_jobs (
  id bigint generated by default as identity primary key,
  music_id bigint not null references public.musics(id) on delete cascade,
  status text not null default 'queued' check (status in ('queued', 'processing', 'completed', 'failed')),
  attempts integer not null default 0,
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  completed_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint music_analysis_jobs_music_unique unique (music_id)
);

create index if not exists music_analysis_jobs_claim_idx
  on public.music_analysis_jobs (status, available_at, id);

alter table public.music_analysis_jobs enable row level security;

revoke all on table public.music_analysis_jobs from anon, authenticated;

create or replace function public.enqueue_music_analysis_job()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.src is not null
     and (nullif(trim(coalesce(new.style, '')), '') is null
          or new.tempo_bpm is null
          or nullif(trim(coalesce(new.rhythm_profile, '')), '') is null) then
    insert into public.music_analysis_jobs (music_id, status, available_at, updated_at)
    values (new.id, 'queued', now(), now())
    on conflict (music_id) do update
      set status = case when music_analysis_jobs.status = 'completed' then 'queued' else music_analysis_jobs.status end,
          available_at = case when music_analysis_jobs.status = 'completed' then now() else music_analysis_jobs.available_at end,
          last_error = case when music_analysis_jobs.status = 'completed' then null else music_analysis_jobs.last_error end,
          updated_at = now();
  end if;
  return new;
end;
$$;

create or replace function public.claim_music_analysis_jobs(p_limit integer default 3)
returns table (
  job_id bigint,
  music_id bigint,
  title text,
  artist text,
  src text,
  genre text,
  style text,
  style_tags text[],
  tempo_bpm numeric,
  rhythm_profile text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidates as (
    select j.id
    from public.music_analysis_jobs j
    where j.status in ('queued', 'failed')
      and j.available_at <= now()
      and j.attempts < 8
    order by j.id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 3), 10))
  ), claimed as (
    update public.music_analysis_jobs j
       set status = 'processing',
           attempts = j.attempts + 1,
           locked_at = now(),
           updated_at = now()
      from candidates c
     where j.id = c.id
    returning j.id, j.music_id
  )
  select c.id, m.id, m.title, m.artist, m.src, m.genre, m.style, m.style_tags,
         m.tempo_bpm, m.rhythm_profile
    from claimed c
    join public.musics m on m.id = c.music_id;
end;
$$;

create or replace function public.complete_music_analysis_job(
  p_job_id bigint,
  p_music_id bigint,
  p_updates jsonb default '{}'::jsonb,
  p_error text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  remaining boolean;
  safe_style text;
  safe_rhythm text;
  safe_tags text[];
  safe_bpm numeric;
  safe_energy numeric;
  safe_dance numeric;
  safe_confidence numeric;
begin
  safe_style := nullif(trim(coalesce(p_updates->>'style', '')), '');
  safe_rhythm := nullif(trim(coalesce(p_updates->>'rhythm_profile', '')), '');
  safe_bpm := case when nullif(p_updates->>'tempo_bpm', '') is null then null else (p_updates->>'tempo_bpm')::numeric end;
  safe_energy := case when nullif(p_updates->>'energy_score', '') is null then null else (p_updates->>'energy_score')::numeric end;
  safe_dance := case when nullif(p_updates->>'danceability_score', '') is null then null else (p_updates->>'danceability_score')::numeric end;
  safe_confidence := case when nullif(p_updates->>'analysis_confidence', '') is null then null else (p_updates->>'analysis_confidence')::numeric end;
  select array(select jsonb_array_elements_text(p_updates->'style_tags')) into safe_tags;

  update public.musics
     set style = coalesce(style, safe_style),
         style_tags = case when coalesce(array_length(style_tags, 1), 0) = 0 and coalesce(array_length(safe_tags, 1), 0) > 0 then safe_tags else style_tags end,
         tempo_bpm = coalesce(tempo_bpm, safe_bpm),
         energy_score = coalesce(energy_score, safe_energy),
         danceability_score = coalesce(danceability_score, safe_dance),
         rhythm_profile = coalesce(rhythm_profile, safe_rhythm),
         analysis_confidence = coalesce(analysis_confidence, safe_confidence),
         analysis_source = coalesce(analysis_source, nullif(trim(coalesce(p_updates->>'analysis_source', '')), '')),
         analysis_version = coalesce(analysis_version, nullif(trim(coalesce(p_updates->>'analysis_version', '')), '')),
         analyzed_at = coalesce(analyzed_at, nullif(p_updates->>'analyzed_at', '')::timestamptz),
         updated_at = now()
   where id = p_music_id;

  select (nullif(trim(coalesce(m.style, '')), '') is null
       or m.tempo_bpm is null
       or nullif(trim(coalesce(m.rhythm_profile, '')), '') is null)
    into remaining
    from public.musics m
   where m.id = p_music_id;

  update public.music_analysis_jobs
     set status = case when coalesce(remaining, true) then 'failed' else 'completed' end,
         available_at = case when coalesce(remaining, true) then now() + interval '15 minutes' else now() end,
         completed_at = case when coalesce(remaining, true) then null else now() end,
         last_error = case when coalesce(remaining, true) then nullif(p_error, '') else null end,
         locked_at = null,
         updated_at = now()
   where id = p_job_id and music_id = p_music_id;
end;
$$;

revoke all on function public.enqueue_music_analysis_job() from public, anon, authenticated;
revoke all on function public.claim_music_analysis_jobs(integer) from public, anon, authenticated;
revoke all on function public.complete_music_analysis_job(bigint, bigint, jsonb, text) from public, anon, authenticated;
grant execute on function public.claim_music_analysis_jobs(integer) to service_role;
grant execute on function public.complete_music_analysis_job(bigint, bigint, jsonb, text) to service_role;

drop trigger if exists music_analysis_enqueue_trigger on public.musics;
create trigger music_analysis_enqueue_trigger
after insert or update of src, style, style_tags, tempo_bpm, rhythm_profile
on public.musics
for each row execute function public.enqueue_music_analysis_job();

insert into public.music_analysis_jobs (music_id)
select m.id
from public.musics m
where m.src is not null
  and (nullif(trim(coalesce(m.style, '')), '') is null
       or m.tempo_bpm is null
       or nullif(trim(coalesce(m.rhythm_profile, '')), '') is null)
on conflict (music_id) do nothing;
