CREATE TABLE IF NOT EXISTS public.music_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requested_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title text NOT NULL CHECK (char_length(btrim(title)) BETWEEN 1 AND 160),
  artist text NOT NULL CHECK (char_length(btrim(artist)) BETWEEN 1 AND 160),
  search_query text,
  source_provider text,
  source_url text,
  cover_url text,
  genre text,
  album text,
  audio_url text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewing', 'approved', 'rejected', 'blocked', 'published')),
  admin_notes text,
  published_music_id bigint REFERENCES public.musics(id) ON DELETE SET NULL,
  reviewed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS music_requests_status_created_idx
  ON public.music_requests (status, created_at DESC);

CREATE INDEX IF NOT EXISTS music_requests_requested_by_idx
  ON public.music_requests (requested_by, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS music_requests_open_identity_idx
  ON public.music_requests (requested_by, lower(title), lower(artist))
  WHERE status IN ('pending', 'reviewing', 'approved');

CREATE OR REPLACE FUNCTION public.set_music_requests_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_music_requests_updated_at ON public.music_requests;
CREATE TRIGGER trg_music_requests_updated_at
BEFORE UPDATE ON public.music_requests
FOR EACH ROW EXECUTE FUNCTION public.set_music_requests_updated_at();

ALTER TABLE public.music_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "music_requests_insert_own" ON public.music_requests;
CREATE POLICY "music_requests_insert_own"
ON public.music_requests FOR INSERT TO authenticated
WITH CHECK (auth.uid() = requested_by);

DROP POLICY IF EXISTS "music_requests_select_own" ON public.music_requests;
CREATE POLICY "music_requests_select_own"
ON public.music_requests FOR SELECT TO authenticated
USING (auth.uid() = requested_by OR public.is_fenda_admin());

DROP POLICY IF EXISTS "music_requests_admin_update" ON public.music_requests;
CREATE POLICY "music_requests_admin_update"
ON public.music_requests FOR UPDATE TO authenticated
USING (public.is_fenda_admin())
WITH CHECK (public.is_fenda_admin());

DROP POLICY IF EXISTS "music_requests_admin_delete" ON public.music_requests;
CREATE POLICY "music_requests_admin_delete"
ON public.music_requests FOR DELETE TO authenticated
USING (public.is_fenda_admin());

CREATE OR REPLACE FUNCTION public.admin_publish_music_request(
  p_request_id bigint,
  p_src text,
  p_cover text DEFAULT NULL,
  p_genre text DEFAULT NULL,
  p_style text DEFAULT NULL,
  p_style_tags text[] DEFAULT NULL,
  p_notes text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_request public.music_requests;
  v_music_id bigint;
BEGIN
  IF NOT public.is_fenda_admin() THEN
    RAISE EXCEPTION 'Apenas administradores podem publicar solicitações';
  END IF;

  IF nullif(btrim(coalesce(p_src, '')), '') IS NULL THEN
    RAISE EXCEPTION 'Um áudio autorizado é obrigatório para publicar';
  END IF;

  SELECT * INTO v_request
  FROM public.music_requests
  WHERE id = p_request_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Solicitação não encontrada';
  END IF;

  IF v_request.status IN ('rejected', 'blocked', 'published') THEN
    RAISE EXCEPTION 'Esta solicitação não pode ser publicada no estado atual';
  END IF;

  INSERT INTO public.musics (
    title, artist, src, cover, lrc, genre, album, release_date,
    track_order, visibility, style, style_tags
  ) VALUES (
    v_request.title,
    v_request.artist,
    p_src,
    COALESCE(NULLIF(btrim(p_cover), ''), v_request.cover_url),
    NULL,
    COALESCE(NULLIF(btrim(p_genre), ''), v_request.genre),
    v_request.album,
    NULL,
    NULL,
    'public',
    NULLIF(btrim(p_style), ''),
    p_style_tags
  )
  RETURNING id INTO v_music_id;

  UPDATE public.music_requests
  SET status = 'published',
      audio_url = p_src,
      cover_url = COALESCE(NULLIF(btrim(p_cover), ''), cover_url),
      genre = COALESCE(NULLIF(btrim(p_genre), ''), genre),
      admin_notes = COALESCE(p_notes, admin_notes),
      published_music_id = v_music_id,
      reviewed_by = auth.uid(),
      reviewed_at = now(),
      updated_at = now()
  WHERE id = p_request_id;

  RETURN v_music_id;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_publish_music_request(bigint, text, text, text, text, text[], text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_publish_music_request(bigint, text, text, text, text, text[], text) TO authenticated;
